### ISSUE TITLE
"Static is not supported for global variables nor required"

### ISSUE THREAD

**Issue by nobledemon** [oskarnp/microui-odin#2]
https://github.com/oskarnp/microui-odin/blob/be82d54387da8acc52142ce4ece96fd61a1e0908/microui.odin#L233

https://github.com/oskarnp/microui-odin/blob/be82d54387da8acc52142ce4ece96fd61a1e0908/microui.odin#L235

These two lines produce the following errors:
```
D:/odin_game/lib/microui-odin/microui.odin(233:9) @(static) is not supported for global variables, nor required
D:/odin_game/lib/microui-odin/microui.odin(235:9) @(static) is not supported for global variables, nor required
```

I'm still sort of completely novice to odin, so I don't feel that confident suggesting a fix, but I assume removing the static flag is not enough

**Comment by oskarnp** [comment]
Removing static for globals was enough. Unlike C, symbols are not exported by default and requires @(export) if so.

**Comment by oskarnp** [comment]
Thank you for the bug report.
